# Generated by Django 4.2.13 on 2024-07-25 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('titular_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('document', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo números.', regex='^\\d+$')])),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('between_street', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cbu', models.CharField(help_text='Ingrese el CBU de 22 dígitos.', max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message='El CBU debe tener exactamente 22 dígitos numéricos.', regex='^\\d{22}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('migrate', models.BooleanField(default=False)),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_stats', 'Can view statistics')],
            },
        ),
        migrations.CreateModel(
            name='Adherente',
            fields=[
                ('adherente_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('document', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo números.', regex='^\\d+$')])),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('between_street', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('migrate', models.BooleanField(default=False)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adherentes', to='pianoadherentes.titular')),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_stats', 'Can view statistics')],
            },
        ),
    ]
