# Generated by Django 4.2.13 on 2024-06-08 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titular',
            name='titular_date',
        ),
        migrations.AddField(
            model_name='titular',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titular',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
