# Generated by Django 4.2.13 on 2024-09-13 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pianoadherentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('adherente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adherentes', to='pianoadherentes.adherente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
