# Generated by Django 4.2.13 on 2024-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='historia',
            field=models.CharField(default='basico', max_length=255),
            preserve_default=False,
        ),
    ]
