# Generated by Django 4.2.13 on 2024-06-09 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0002_remove_titular_titular_date_titular_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherente',
            name='dni',
            field=models.CharField(default=0, max_length=100, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo números.', regex='^\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='titular',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
