# Generated by Django 4.2.13 on 2024-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0006_alter_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherente',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
