# Generated by Django 4.2.13 on 2024-09-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0008_datosuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='datosuser',
            name='sucursal',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.PROTECT, to='pianoadherentes.sucursales'),
            preserve_default=False,
        ),
    ]
