# Generated by Django 4.2.13 on 2024-09-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0009_sucursales_datosuser_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pianoadherentes.sucursales'),
        ),
    ]
