# Generated by Django 4.2.13 on 2024-09-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0011_alter_log_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titular',
            options={'permissions': [('can_view_stats', 'Can view statistics'), ('can_view_stats_controller', 'Can view statistics controller')]},
        ),
        migrations.AddField(
            model_name='adherente',
            name='legajo',
            field=models.IntegerField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adherente',
            name='sucursal',
            field=models.CharField(blank=True, max_length=50),
            preserve_default=False,
        ),
    ]
