# Generated by Django 4.2.13 on 2024-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0012_alter_titular_options_adherente_legajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherente',
            name='sucursal',
            field=models.CharField(max_length=50),
        ),
    ]
