# Generated by Django 4.2.13 on 2024-10-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pianoadherentes', '0013_alter_adherente_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
