# Generated by Django 4.2.13 on 2025-06-05 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pianoadherentes', '0013_alter_adherente_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titular',
            options={'permissions': [('can_view_stats', 'Can view statistics'), ('can_view_stats_controller', 'Can view statistics controller'), ('can_view_stats_controllerAdmin', 'Can view statistics controller Admin')]},
        ),
        migrations.AddField(
            model_name='titular',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
