# Generated by Django 4.2.13 on 2024-10-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0014_alter_datosuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titular',
            options={'permissions': [('can_view_stats', 'Can view statistics'), ('can_view_stats_controller', 'Can view statistics controller'), ('can_view_stats_controllerAdmin', 'Can view statistics controller Admin')]},
        ),
    ]
