# Generated by Django 4.2.13 on 2025-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0014_alter_titular_options_titular_nro_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
