# Generated by Django 4.2.13 on 2026-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0015_alter_titular_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='titular',
            name='plan',
            field=models.CharField(blank=True, default='Basico', max_length=20, null=True),
        ),
    ]
