# Generated by Django 4.2.13 on 2025-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0015_alter_titular_nro_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='nro_sucursal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
