# Generated by Django 4.2.13 on 2024-10-31 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pianoadherentes', '0015_alter_titular_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('prestamos_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=10)),
                ('document', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El DNI debe contener solo números.', regex='^\\d+$')])),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('between_street', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cbu', models.CharField(blank=True, help_text='Ingrese el CBU de 22 dígitos.', max_length=22, null=True, validators=[django.core.validators.RegexValidator(message='El CBU debe tener exactamente 22 dígitos numéricos.', regex='^\\d{22}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('migrate', models.BooleanField(default=False)),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('date_init', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('titular_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='pianoadherentes.prestamos')),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
