# Generated by Django 4.2.13 on 2024-10-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0016_prestamos_contratos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='document_type',
        ),
    ]
