# Generated by Django 4.2.13 on 2024-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0017_remove_prestamos_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='legajo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='sucursal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
