# Generated by Django 4.2.13 on 2024-11-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianoadherentes', '0018_contratos_is_active_contratos_legajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
